version: "3.7"
services:
  homeassistant:
    image: ghcr.io/matthewbaggett/full-control-home-assistant:test
    ports:
      - "8123:8123"
  fullcontrol:
    image: ghcr.io/matthewbaggett/full-control-home-assistant:test
    volumes:
      - ./config:/fullcontrol
      - ../Full-Control-Home-Assistant:/usr/src/fullcontrol
