version: "3.7"

volumes:
  postgres:

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: &postgres_username fullcontrol
      POSTGRES_PASSWORD: &postgres_password fullcontrol
      POSTGRES_DB: &postgres_db homeassistant
    ports:
      - "127.0.0.33:5432:5432"

  homeassistant:
    build: ../Full-Control-Home-Assistant
    depends_on: [ postgres ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./ha-config:/config:rw
      - ./logs:/var/logs
    ports:
      - "127.0.0.33:8123:8123"

  homeassistant-default:
    build: ../Full-Control-Home-Assistant
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./ha-config-default:/config:rw
      - ./logs2:/var/logs
    ports:
      - "127.0.0.34:8123:8123"

  fullcontrol:
    build: ../Full-Control-Home-Assistant
    image: ghcr.io/matthewbaggett/full-control-home-assistant:latest
    depends_on: [ homeassistant ]
    command: [ "fullcontrol", "-w", "/fullcontrol"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./ha-config:/config:rw
      - ./config:/fullcontrol:ro
      - ../Full-Control-Home-Assistant:/usr/src/fullcontrol
    environment:
      FULLCONTROL_READONLY: false
      DATABASE_TYPE: postgresql
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_DATABASE: *postgres_db
      DATABASE_USERNAME: *postgres_username
      DATABASE_PASSWORD: *postgres_password
